name: data_app
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.5
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - greenlet==3.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - imbalanced-learn==0.12.2
      - importlib-metadata==7.2.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.2.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langchain==1.2.3
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.7
      - langchain-openai==1.1.7
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.6
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.6
      - langgraph-sdk==0.3.3
      - langsmith==0.6.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nltk==3.8.1
      - numpy==1.26.4
      - openai==2.15.0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - packaging==23.2
      - pandas==2.2.0
      - patsy==1.0.2
      - pillow==10.4.0
      - plotly==5.18.0
      - propcache==0.4.1
      - protobuf==4.25.8
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.0.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.30.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - statsmodels==0.14.2
      - streamlit==1.31.0
      - streamlit-lottie==0.0.5
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - toml==0.10.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - urllib3==2.6.3
      - uuid-utils==0.13.0
      - validators==0.35.0
      - watchdog==6.0.0
      - wordcloud==1.9.3
      - xgboost==2.0.3
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: O:\SteamLibrary\apps\Miniconda_Envs\data_app
